spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:D:/IdeaProjects/spring-boot-hibernate/database/src/main/resources/countries;MV_STORE=false;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
logging:
  level:
    root: info
